version: '3.8'

services:
  svd-tensorrt:
    build: .
    container_name: svd-tensorrt-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./models:/workspace/models
      - ./output:/workspace/output
      - ./engines:/workspace/engines
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "7860:7860"  # For potential web interface
    stdin_open: true
    tty: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  default:
    name: svd-network
